### ISSUE TITLE
Bins upper limit

### ISSUE THREAD

**Issue by JustTestingGo** [vondoRishi/AdvanceOfficeChart#1]
Is there any way that you can manually define the upper limits of the bins in histograms?

Thank you!

**Comment by vondoRishi** [comment]
At present the maximum number of bins are set to 100. It is not possible to manually increase further. I will try to set it to 1000 in next release.

Thanks for your feedback.

**Comment by JustTestingGo** [comment]
Thanks for your answer, but what I really meant is if there's a way to set the upper limits of the bins (not the number of bins). For example, imagine that I want to create 10 bins but I want the upper limits of each bin this way:
1st bin -> Upper limit 12
2nd bin -> Upper limit 22
3rd bin -> Upper limit 32
4th bin -> Upper limit 42
5th bin -> Upper limit 52
6th bin -> Upper limit 62
7th bin -> Upper limit 72
8th bin -> Upper limit 82
9th bin -> Upper limit 92
10th bin -> Upper limit 102

Thank you!

**Comment by vondoRishi** [comment]
Hi ,
The functionality is limited to [HistogramDataset](http://www.jfree.org/jfreechart/api/javadoc/org/jfree/data/statistics/HistogramDataset.html) from JfreeChart library.Therefore it is not possible now as you have suggested.

Thanks for your comment.
