### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by thsfo** [vondoRishi/AdvanceOfficeChart#2]
Hello,
When i try to activate this extension, there is a java error: java.lang.reflect.InvocationTargetException
In libreoffice 4.3.3.2 Debian JESSIE

bye

**Comment by vondoRishi** [comment]
Please let us know about the "Java runtime environment " version.

**Comment by LabunskyA** [comment]
Same on:
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

**Comment by vondoRishi** [comment]
Hi ,
I can not reproduce the problem. However there are same problem with other extension reported in the web. see https://code.google.com/archive/p/ooo2gd/issues/115 

 try this: 
1)After installing Java, open LibreOffice>Tools>Options>Advanced>Select JRE to Use. 
2)Close Libre Office 
3)Then install libreoffice-java-common using sudo apt-get install libreoffice-java-common 
4)Now start LibreOffice and Enable the extension. 
5)Plugin should work now.
