### ISSUE TITLE
Cannot create Java implementation loader

### ISSUE THREAD

**Issue by iconmaster5326** [vondoRishi/AdvanceOfficeChart#3]
I am on a Windows 10 machine running LibreOffice 5.2.5.1. When I try to use your installer to install this extension, I get the following error message:

```
Cannot create Java implementation loader
```

And the plugin does not install.

**Comment by vondoRishi** [comment]
Hi ,
This error most likely happen due to faulty installation of java . 
Please follow this [link](https://www.zotero.org/support/word_processor_plugin_troubleshooting#could_not_create_java_implementation_loader) to solve the problem.

**Comment by thakardarshit** [comment]
The solution was to install the Java development kit (JDK). Once that was installed and path added to environment variables https://www.poftut.com/how-to-set-java-jre-and-jdk-home-path-and-environment-variables-on-windows/ , all versions of the runtime (JRE) appeared in LibreOffice and the plugin installed successfully.
