### ISSUE TITLE
Usage with Debian11

### ISSUE THREAD

**Issue by gnasch** [vondoRishi/AdvanceOfficeChart#7]
20221114 cg
Using 
~$ cat /etc/debian_version
11.5

and Libreoffice: 
Version: 7.0.4.2
Build ID: 00(Build:2)
CPU threads: 2; OS: Linux 5.10; UI render: default; VCL: kf5
Locale: de-CH (de_CH.utf8); UI: de-DE
Debian package version: 1:7.0.4-4+deb11u4
Calc: threaded
(This is a german-localized version.)

I installed libfreechart-java with apt, 
installed the extension by the extension manager.
No new menu item showed up within the "Extras" menu.
An "Advanced Office Charts" Icon showed up on a new "Symbolleiste".

When selecting data and pressing the icon, strictly nothing happened.
apt install openjdk-17-jre and a reboot resolved the issue.
Now everything works nicely. 
Thank you!!!
Maybe the dependencies could be more clearly mentioned in the README?

**Comment by vondoRishi** [comment]
ReadME is updated.
Thanks for reporting this.
